### ISSUE TITLE
in IOS it still stuck on top if internet back to online

### ISSUE THREAD

**Issue by Tanzeel-ur-rehman-git** [WrathChaos/react-native-internet-connection-alert#7]
this is my app.js code

```
 return (
    <SafeAreaProvider>
      <CustomStatusBar backgroundColor="#5CA2E2" />
    <InternetConnectionAlert
      onChange={connectionState => {
        // console.log("Connection State: ", connectionState)
      }}>
        
      <Provider store={store}>
        <NavigationContainer>
          <HomeStackNavigation />
          <Toast />
        </NavigationContainer>
      </Provider>
    </InternetConnectionAlert>
    </SafeAreaProvider>
  );
```

**Dependencies** 
```
"react-native-internet-connection-alert": "^0.1.7",
"react-native-dropdownalert": "4.5.1",
@react-native-community/netinfo": "8.0.0",
```

on android above 10 version, it works fine but below 9 it stuck on top even after the internet is back to online

**Comment by kuraydev** [comment]
Hello @Tanzeel-ur-rehman-git,
Thank you for reporting this. I will take a look at it ASAP

**Comment by HarshitMadhav** [comment]
any update on this?

**Comment by OmkarArote** [comment]
Any update on this?

**Comment by OmkarArote** [comment]
Facing the same issue in Andoird too!

**Comment by kuraydev** [comment]
I'm going to fix it today. Sorry for late fix

**Comment by OmkarArote** [comment]
Thanks, @WrathChaos !

**Comment by OmkarArote** [comment]
Any updates @WrathChaos ?

**Comment by kuraydev** [comment]
Hello @OmkarArote , @HarshitMadhav , @Tanzeel-ur-rehman-git 

I've updated the [example](https://github.com/WrathChaos/react-native-internet-connection-alert/tree/master/example), also tested it seems work with real devices. 

Actually, all you need to do is upgrade the 
```
"@react-native-community/netinfo": "^8.3.0",
"react-native-dropdownalert": "4.5.1"
```
dependencies. Can you also test it with me?

**Comment by kuraydev** [comment]
I released a new version: [Version 0.1.8 🍺](https://github.com/WrathChaos/react-native-internet-connection-alert/releases/tag/0.1.8)

Also tested with both iOS and Android real devices. It works on my tests. 

Please try to upgrade the peer dependencies and the library itself. 

@OmkarArote  @HarshitMadhav @Tanzeel-ur-rehman-git

**Comment by OmkarArote** [comment]
https://user-images.githubusercontent.com/64545577/167271867-b66db1eb-15c4-4f83-9bbd-d09f9a474599.mp4

@WrathChaos I am still facing the same issue
The alert is not async with the network change

Dependencies:
<pre>
"react-native-dropdownalert": "^4.5.1",
"react-native-internet-connection-alert": "^0.1.8",
"@react-native-community/netinfo": "^8.3.0",
</pre>

My Code:
```
return (
      <InternetConnectionAlert
        onChange={(connectionState) => {
          console.log("Connection State: ", connectionState);
        }}
      >
        <View style={{ flex: 1 }}>
          <NavigationContainer>
            <GalioProvider theme={argonTheme}>
              <Block flex>
                <Screens />
              </Block>
            </GalioProvider>
          </NavigationContainer>
          <FlashMessage position="top" />
        </View>
      </InternetConnectionAlert>
    );
```

**Comment by kuraydev** [comment]
@OmkarArote Can you test the same with physical device?

**Comment by OmkarArote** [comment]
> @OmkarArote Can you test the same with physical device?

Yea tested it on a physical device too
Same issue!

**Comment by kuraydev** [comment]
I will look at it @OmkarArote

**Comment by mariomurrent-softwaresolutions** [comment]
It could be a problem with the @react-native-community/netinfo package => https://github.com/react-native-netinfo/react-native-netinfo/issues/573

This issue is still open

**Comment by kuraydev** [comment]
Thank you for let us know @mariomurrent-softwaresolutions 

@OmkarArote 
Are you using low level react-native version?

**Comment by hamfer** [comment]
I don't know if this is the fix.
Just added closeAction before alert
![image](https://user-images.githubusercontent.com/40804567/181417485-067cb3ce-7230-4b16-b0f6-5c293f3d5db9.png)
Need more testing

**Comment by kuraydev** [comment]
> I don't know if this is the fix. Just added closeAction before alert ![image](https://user-images.githubusercontent.com/40804567/181417485-067cb3ce-7230-4b16-b0f6-5c293f3d5db9.png) Need more testing

Unfortunately, this is not an issue for dropdown alert library. This is an issue because of this: https://github.com/react-native-netinfo/react-native-netinfo/issues/573
